[phases.build]
cmds = [
  "python -m nltk.downloader averaged_perceptron_tagger punkt stopwords wordnet vader_lexicon -d /usr/local/nltk_data",
  "chmod +x /app/start.sh"
]

[start]
cmd = "bash /app/start.sh"
