[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "python -m nltk.downloader averaged_perceptron_tagger punkt stopwords wordnet vader_lexicon -d /usr/local/nltk_data"
]

[start]
cmd = "bash start.sh"
